export const DEFAULT_INGREDIENTS: Record<string, number> = {

  // ── VIANDES BOUCHERIE ──────────────────────────
  "Bœuf - Filet":              58.0,
  "Bœuf - Entrecôte":          32.0,
  "Bœuf - Faux-filet":         28.0,
  "Bœuf - Côte de bœuf":       26.0,
  "Bœuf - Paleron":            12.5,
  "Bœuf - Joue":               14.0,
  "Bœuf - Bavette":            18.0,
  "Bœuf - Macreuse":           11.0,
  "Bœuf - Plat de côte":        9.0,
  "Veau - Escalope":           24.0,
  "Veau - Côte":               28.0,
  "Veau - Joue":               18.0,
  "Veau - Jarret":             14.0,
  "Veau - Tendron":            12.0,
  "Agneau - Gigot entier":     15.0,
  "Agneau - Épaule":           12.0,
  "Agneau - Rack / carré":     28.0,
  "Agneau - Côtelette":        22.0,
  "Agneau - Souris":           16.0,
  "Agneau - Selle":            24.0,
  "Agneau - Navarin":          10.0,
  "Porc - Filet mignon":       14.0,
  "Porc - Côte":               10.0,
  "Porc - Joue":                8.0,
  "Porc - Lard fumé":           7.5,
  "Porc - Travers":             8.5,
  "Porc - Pied":                5.0,

  // ── VOLAILLES ──────────────────────────────────
  "Poulet - Filet":            10.0,
  "Poulet - Cuisse":            6.5,
  "Poulet - Suprême":          12.0,
  "Poulet - Entier":            5.5,
  "Canard - Magret":           22.0,
  "Canard - Confit de cuisse": 14.0,
  "Canard - Foie gras entier": 80.0,
  "Canard - Escalope foie gras":90.0,
  "Pintade - Filet":           18.0,
  "Pintade - Entière":         10.0,
  "Caille - Entière":          12.0,
  "Pigeon - Entier":           18.0,
  "Lapin - Entier":             8.0,
  "Lapin - Râble":             14.0,

  // ── POISSONS ───────────────────────────────────
  "Saumon - Filet":            18.0,
  "Saumon - Pavé":             20.0,
  "Cabillaud - Filet":         15.0,
  "Cabillaud - Dos":           22.0,
  "Bar - Filet":               28.0,
  "Bar - Entier":              18.0,
  "Daurade - Filet":           22.0,
  "Daurade - Entière":         14.0,
  "Thon rouge - Pavé":         35.0,
  "Sole - Filet":              42.0,
  "Turbot - Filet":            55.0,
  "Lotte - Queue":             22.0,
  "Maquereau - Filet":          8.0,
  "Sardine - Fraîche":          5.0,
  "Rouget - Filet":            32.0,
  "Flétan - Filet":            28.0,

  // ── CRUSTACÉS & COQUILLAGES ────────────────────
  "Saint-Jacques - Noix":      38.0,
  "Crevettes roses décortiquées":22.0,
  "Gambas - Entières":         28.0,
  "Homard breton - Entier":    55.0,
  "Langoustines":              42.0,
  "Écrevisses":                35.0,
  "Moules de bouchot":          3.5,
  "Huîtres creuses":            8.0,
  "Palourdes":                 14.0,
  "Poulpe":                    12.0,
  "Calamars":                  12.0,
  "Seiche":                    10.0,

  // ── LÉGUMES ────────────────────────────────────
  "Pomme de terre - Bintje":    1.1,
  "Pomme de terre - Charlotte": 1.5,
  "Pomme de terre grenaille":   2.5,
  "Carotte":                    1.0,
  "Carotte fane":               2.5,
  "Oignon jaune":               0.9,
  "Oignon rouge":               1.2,
  "Échalote":                   4.0,
  "Ail":                        5.0,
  "Tomate ronde":               2.0,
  "Tomate cerise":              4.5,
  "Tomate cœur de bœuf":        4.0,
  "Courgette":                  2.0,
  "Aubergine":                  2.5,
  "Poivron rouge":              3.0,
  "Poivron jaune":              3.5,
  "Champignon de Paris":        5.0,
  "Cèpes frais":               35.0,
  "Girolles":                  40.0,
  "Morilles fraîches":        120.0,
  "Truffe noire Périgord":    800.0,
  "Truffe d'été":             180.0,
  "Épinard frais":              4.0,
  "Asperge verte":              8.0,
  "Asperge blanche":           10.0,
  "Artichaut":                  4.0,
  "Brocoli":                    2.5,
  "Chou-fleur":                 2.0,
  "Haricot vert extra-fin":     6.0,
  "Petits pois frais":          4.0,
  "Fèves":                      5.0,
  "Fenouil":                    2.5,
  "Poireau":                    2.0,
  "Céleri branche":             2.0,
  "Céleri rave":                1.8,
  "Endive":                     3.0,
  "Salade verte":               2.5,
  "Roquette":                   8.0,
  "Mâche":                     10.0,
  "Betterave cuite":            2.0,
  "Potiron":                    1.5,
  "Pâtisson":                   3.0,
  "Maïs frais":                 2.0,

  // ── PRODUITS LAITIERS ──────────────────────────
  "Beurre doux":                9.0,
  "Beurre clarifié":           11.0,
  "Crème fraîche épaisse":      4.5,
  "Crème liquide 30% MG":       3.8,
  "Crème liquide 35% MG":       5.0,
  "Lait entier":                1.2,
  "Parmesan - Reggiano":       24.0,
  "Gruyère râpé":              12.0,
  "Comté 18 mois":             18.0,
  "Mozzarella di bufala":      14.0,
  "Burrata":                   18.0,
  "Chèvre frais":              14.0,
  "Roquefort":                 22.0,
  "Camembert":                 12.0,
  "Reblochon":                 16.0,
  "Ricotta":                    8.0,
  "Mascarpone":                 9.0,

  // ── ÉPICERIE SÈCHE ─────────────────────────────
  "Farine T45":                 1.2,
  "Farine T55":                 0.9,
  "Riz long grain":             1.8,
  "Riz arborio":                3.5,
  "Riz basmati":                3.0,
  "Pâtes fraîches":             5.0,
  "Pâtes sèches":               2.2,
  "Gnocchis frais":             6.0,
  "Lentilles vertes du Puy":    4.0,
  "Lentilles corail":           3.0,
  "Pois chiches":               2.8,
  "Flageolets":                 3.5,
  "Quinoa":                     5.0,
  "Huile d'olive vierge extra": 9.0,
  "Huile de tournesol":         2.5,
  "Huile de sésame":           12.0,
  "Vinaigre balsamique":        8.0,
  "Vinaigre de xérès":          6.0,
  "Moutarde de Dijon":          5.0,
  "Concentré de tomate":        3.5,
  "Câpres":                    12.0,
  "Anchois à l'huile":         22.0,
  "Tapenade":                  10.0,
  "Sauce soja":                 5.0,
  "Sauce Worcestershire":        8.0,

  // ── AROMATES & ÉPICES ──────────────────────────
  "Thym frais":                  8.0,
  "Romarin frais":               8.0,
  "Basilic frais":              12.0,
  "Persil plat":                 6.0,
  "Coriandre fraîche":           8.0,
  "Estragon frais":             10.0,
  "Ciboulette":                  8.0,
  "Laurier":                     6.0,
  "Herbes de Provence":         14.0,
  "Sel fin":                     0.5,
  "Fleur de sel":               20.0,
  "Poivre noir concassé":       15.0,
  "Poivre de Sichuan":          35.0,
  "Cumin":                      10.0,
  "Paprika doux":                8.0,
  "Paprika fumé":               12.0,
  "Curcuma":                    10.0,
  "Curry":                       8.0,
  "Piment d'Espelette":         60.0,
  "Safran (pistils)":         3500.0,
  "Cannelle":                   12.0,
  "Cardamome":                  40.0,
  "Noix de muscade":            20.0,
  "Vanille (gousse)":          200.0,

  // ── ALCOOLS CUISINE ────────────────────────────
  "Vin blanc sec":               5.0,
  "Vin rouge":                   4.5,
  "Champagne":                  18.0,
  "Porto rouge":                12.0,
  "Porto blanc":                12.0,
  "Cognac":                     25.0,
  "Calvados":                   20.0,
  "Armagnac":                   22.0,
  "Xérès sec":                  10.0,
  "Pastis":                     15.0,
  "Fond de veau lié":            9.0,
  "Fond de volaille":            7.0,
  "Fond de poisson":             8.0,
  "Fumet de crustacés":         12.0,

  // ── SUCRÉ & PÂTISSERIE ─────────────────────────
  "Sucre blanc":                 1.0,
  "Sucre glace":                 1.5,
  "Sucre cassonade":             2.0,
  "Glucose":                     3.5,
  "Chocolat noir 70%":          12.0,
  "Chocolat au lait":           10.0,
  "Chocolat blanc":             11.0,
  "Cacao en poudre":            12.0,
  "Miel de fleurs":              8.0,
  "Caramel liquide":             4.0,
  "Praliné":                    14.0,
  "Pâte d'amande":              12.0,
  "Gélatine (feuilles)":        25.0,
  "Agar-agar":                  40.0,
  "Levure boulangère":           5.0,

  // ── ŒUFS ───────────────────────────────────────
  "Œuf entier":                  0.35,
  "Jaune d'œuf":                 0.5,
  "Blanc d'œuf":                 0.2,

  // ── FRUITS ─────────────────────────────────────
  "Citron jaune":                2.0,
  "Citron vert":                 3.5,
  "Orange":                      1.8,
  "Pomme Golden":                1.5,
  "Poire Williams":              2.5,
  "Fraise Gariguette":           8.0,
  "Framboise":                  16.0,
  "Myrtille":                   14.0,
  "Cerise":                      6.0,
  "Pêche":                       3.0,
  "Abricot":                     3.5,
  "Mangue":                      4.0,
  "Ananas":                      3.0,
  "Avocat":                      3.5,
  "Figue fraîche":               6.0,
  "Raisin blanc":                4.0,
  "Banane":                      1.8,
  "Fruits de la passion":        8.0,
}

export const INGREDIENT_NAMES = Object.keys(DEFAULT_INGREDIENTS).sort()

export const getPriceForIngredient = (
  name: string,
  customPrices: Record<string, number> = {}
): number => {
  if (customPrices[name]) return customPrices[name]
  return DEFAULT_INGREDIENTS[name] ?? 5.0
}
